{
 "title": "Flask Dashboard",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "label": "Pod name",
    "query": {
     "query": "label_values(app_version_info, pod)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(app_request_latency_seconds_bucket, exported_endpoint)"
    }
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(app_request_latency_seconds_bucket, method)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": {
     "query": "label_values(app_request_count_total, http_status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Flask app - Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "piechart",
   "gridPos": { "h": 22, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_request_count_total{method=\"GET\"})",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(app_request_count_total{method=\"OPTIONS\"})",
     "legendFormat": "OPTIONS"
    },
    {
     "expr": "sum(app_request_count_total{method=\"POST\"})",
     "legendFormat": "POST (LIKE)"
    }
   ]
  },
  {
   "title": "Request Latency, s",
   "type": "timeseries",
   "description": "Latency per pod, endpoint and method",
   "gridPos": { "h": 11, "w": 11, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_request_latency_seconds_sum{pod=~\"$pod\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$interval]) \n/ \nrate(app_request_latency_seconds_count{pod=~\"$pod\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])",
     "legendFormat": "{{ method }} {{ pod }}{{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_request_count_total{http_status=~\"$error_code\", pod=~\"$pod\", method=~\"$method\", exported_endpoint=~\"$endpoint\"}",
     "legendFormat": "{{ http_status }} {{ pod }} {{ exported_endpoint }}"
    },
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second ",
   "gridPos": { "h": 11, "w": 11, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(app_request_count_total{pod=~\"$pod\", exported_endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])",
     "legendFormat": "{{ method }} {{ pod }} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_request_count_total{http_status=~\"4..|5..\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": " Errors per second"
    },
    {}
   ]
  },
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "graph",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(app_request_latency_seconds_bucket[$interval])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"$pod\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}