version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts: 
            - "host.docker.internal:host-gateway"
        command: 'python manage.py runserver 0.0.0.0:8000'
        ports:
            - 8000:8000
        volumes: 
            - .:/app
        depends_on: 
            - db

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python consumer.py'
        depends_on: 
            - db

    
    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWAORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - .dbdata:/var/lib/mysql
        ports:
            - 33066:3306

    promethus:
        image: prom/prometheus
        volumes: 
            - ./prometheus/:/etc/prometheus/
        ports:
            - 9000:9000
